### ISSUE TITLE
chat 部分参数描述不正确

### ISSUE THREAD

**Issue by zyp1573** [xiexin12138/OpenAI-API-Chinese#1]
api-reference  Create chat completion接口与Create completion部分参数名一致  但是参数默认值与参数描述并不同。

**Comment by jiahim** [comment]
感谢反馈，我检查后更新下！

**Comment by jiahim** [comment]
> api-reference Create chat completion接口与Create completion部分参数名一致 但是参数默认值与参数描述并不同。

已经在最新的commit改正，请确认下

**Comment by zyp1573** [comment]
> > api-reference Create chat completion接口与Create completion部分参数名一致 但是参数默认值与参数描述并不同。
> 
> 已经在最新的commit改正，请确认下

🫡  感谢
