### ISSUE TITLE
创建图片编辑接口缺少mask参数

### ISSUE THREAD

**Issue by zyp1573** [xiexin12138/OpenAI-API-Chinese#2]
RT

**Comment by zyp1573** [comment]
mask | string | / | / | 附加的图像中完全透明的区域（例如 alpha 为零的区域）指示图像应该被编辑的位置。必须是有效的 PNG 文件，大小不超过 4MB，并且具有与图像相同的尺寸。

**Comment by zyp1573** [comment]
创建图像变化接口缺少接口描述

**Comment by zyp1573** [comment]
> Author

创建给定图像的变体。

**Comment by zyp1573** [comment]
创建图片变化接口接口参数有误  文档中没有prompt参数

**Comment by jiahim** [comment]
感谢 @zyp1573 的反馈！
已修正，请检查：
增加1处：编辑图像接口mask参数
删除1处：创建变化接口prompt参数

**Comment by zyp1573** [comment]
> 感谢 @zyp1573 的反馈！ 已修正，请检查： 增加1处：编辑图像接口mask参数 删除1处：创建变化接口prompt参数
🫡
